### ISSUE TITLE
-recode-allele export_allele_ids

### ISSUE THREAD

**Issue by johnacurtin** [immunogenomics/HLA_analyses_tutorial#1]
Hi, 
I am giving your paper a go and it looks really nice. Just one query,
What does the file -recode-allele **export_allele_ids** correspond to. I don't seem to generate this file anywhere. can you let me know the origin of this file, 

This is from the part of your page at: 
Outputs:
SNP2HLA.py outputs a single phased and imputed vcf file: {output}.bgl.phased.vcf.gz, that can be recoded to a tabular, raw dosage format using plink. This can be accomplished via the following command, where {output}_allele_ids is a file with variant ids and the corresponding desired allele to be counted:

plink --vcf hgdp_chr6.final.SNP2HLApy.imputed.bgl.phased.vcf.gz dosage=DS --recode A --recode-allele export_allele_ids --out hgdp_chr6.final.SNP2HLApy.imputed

Many thanks
John

**Comment by saorisakaue** [comment]
Hi John,

I apologize my delayed response and thanks for pointing out!

We revised this command now by using `plink2` as follows:
`plink2 --vcf hgdp_chr6.final.SNP2HLApy.imputed.bgl.phased.vcf.gz dosage=DS --export A --export-allele export_allele_ids --out hgdp_chr6.final.SNP2HLApy.imputed`

`export_allele_ids` is a text file specifying the variant and the effect allele we'd like to output by this command.
https://www.cog-genomics.org/plink/2.0/data
"--export-allele's input file should have variant IDs in the first column and allele IDs in the second"

If you would like to output the ALT dosage of each variant, it can be created by
`zcat hgdp_chr6.final.SNP2HLApy.imputed.bgl.phased.vcf.gz | grep -v "#" | cut -f3,5`

I hope this helps and feel free to let us know if you have any additional questions.

Thanks,
Saori

**Comment by johnacurtin** [comment]
Dear Saori,

I have tried your suggestion and it seems to work. Can I just confirm so I am absolutely sure: For the purposes of this methodology the desired allele is the ALT allele? Therefore when following the intention of your methodology I need to first do:

zcat hgdp_chr6.final.SNP2HLApy.imputed.bgl.phased.vcf.gz | grep -v "#" | cut -f3,5 > export_allele_id
## and then

plink2 --vcf hgdp_chr6.final.SNP2HLApy.imputed.bgl.phased.vcf.gz dosage=DS --export A --export-allele export_allele_ids --out hgdp_chr6.final.SNP2HLApy.imputed

Many thanks
John

**Comment by saorisakaue** [comment]
Hi John,

Yes, your commands are correct! First generate the export_allele_id file and then supply it to the plink2 to obtain matrix of genotype dosage.
I do not have any strong suggestions on the SNPs, but I do think for HLA alleles and amino acids, the effect allele should be "T", which should be ALT of each variant (please confirm!) and represents the probability of "presence" of the alleles/amino acids, just to be easily interpretable.

Best,
Saori
