### ISSUE TITLE
HLA type?

### ISSUE THREAD

**Issue by psychrb** [immunogenomics/HLA_analyses_tutorial#4]
Please clarify: For this pipeline (**tutorial_HLAQCImputation.ipynb**) using the Michigan server for a multi-ancestry cohort, how can one convert the output imputed SNPs to conventional HLA haplotype/HLA allele nomenclature, for each individual? It seems this program can only return HLA imputed SNPs,no...? 
Or, pls advise: How to convert allele name (CHR:POS) or set of SNPs to conventional HLA nomenclature (HLA_A*XX:XX) in the output VCF file?

**Comment by LiuYunjia** [comment]
have you converted the output umputed SNPs to HLA allele for each individual？
